### ISSUE TITLE
Support `stylelint>=9.1` as peerDependencies

### ISSUE THREAD

**Issue by sobolevn** [stylelint/jest-preset-stylelint#11]
Currently, `jest-preset-stylelint` has a strict rule that it works with only `stylelint^9.1.3`

Which is not actually correct.
It works perfectly with `stylelint@11` and `stylelint@12`, I am using it a lot in some of my projects.
The only issue is in the warning it produces:

```
warning " > jest-preset-stylelint@1.3.0" has incorrect peer dependency "stylelint@^9.1.3".
```

Here: https://github.com/stylelint/jest-preset-stylelint/blob/master/package.json#L43

**Comment by ntwb** [comment]
Thanks, glad you've found this package useful, I updated the `peerDependencies` to support stylelint v10, v11, & v12

I'm going to hold of on releasing this update, there's been some recent changes to the Jest setup in styleint upstream, so I'll get these changes added to this repo
