### ISSUE TITLE
getTestRule.js:16:31 -  A dynamic import callback was invoked without --experimental-vm-modules

### ISSUE THREAD

**Issue by scottlikestech** [stylelint/jest-preset-stylelint#120]
### What steps are needed to reproduce the bug?

Install latest versions of: 
"stylelint": "16.9.0",
"jest": "29.7.0",
"jest-preset-stylelint": "7.1.0",

Then in node, run: jest

tsconfig.json
{
	"compileOnSave": false,
	"compilerOptions": {
        "allowJs": false,
		"baseUrl": "./",
		"declaration": false,
		"emitDecoratorMetadata": false,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"importHelpers": false,
		"module": "esnext",
		"moduleResolution": "bundler",
		"outDir": "./dist",
		"removeComments": true,
		"resolveJsonModule": true,
		"sourceMap": false,
		"strict": true,
		"target": "ES2022",
		"typeRoots": [
			"node_modules/@types"
		]
	}
}

spec file - error on testRule.getTestRule()

import testRule, { TestSchema } from 'jest-preset-stylelint';
import { ruleName, errorMessage } from './no-grayscale';

const schema: TestSchema = {
    plugins: ['./src/rules/scss/no-grayscale/no-grayscale.ts'],
    ruleName,
    config: true,
    fix: false,	
    accept: [
    {
        code: `.myclass {
            /*filter: grayscale(0);*/
        }`,
        description: 'Ignore usage if in comment.'
    }],
	reject: []	
};

const runRule = testRule.getTestRule();
runRule(schema);

### What did you expect to happen?

Jest completes with 1 passed test

### What actually happened?

getTestRule.js:16:31 -  A dynamic import callback was invoked without --experimental-vm-modules

Why the error?
And how do you turn on --experimental-vm-modules in the context of a single node command?

**Comment by ybiquitous** [comment]
@scottlikestech Thanks for the report. The issue seems to be due to the TypeScript settings. Can you provide a reproducible repository?

**Comment by scottlikestech** [comment]
I fixed this issue.  There is another issue after but will log that separately if I can't fix myself.

I am using Node 20.17.0 and apparently since Node 20.10 it requires --experimental-vm-modules flag for dynamic imports, which your getTestRule.js uses.  So I change by npm build command in package.json accordingly:

"scripts": {
    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js",
},
