### ISSUE TITLE
Add JSDoc for testRule

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/jest-preset-stylelint#15]
For better editor integration (especially VS Code) I would like to add JSDoc to a `testRule`. This way editor would help working with testRule with useful autocomplete.

**Comment by hudochenkov** [comment]
After [wondering around](https://github.com/stylelint/jest-preset-stylelint/commits/jsdoc) it a bit, we might need to provide stylelint first-party TypeScript declarations and setup TypeScript first https://github.com/stylelint/stylelint/issues/4399

**Comment by jeddy3** [comment]
This seems like an ideal time to do that as we'll be dogfooding in this repository our own exported declarations.

**Comment by hudochenkov** [comment]
I'll try to look into it coming week.
