### ISSUE TITLE
Jest peerDependency

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/jest-preset-stylelint#2]
https://github.com/stylelint/jest-preset-stylelint/commit/1165c6c0e71819b8c8e1e83d095ff0989692c97a

I wanted to make a PR, but made a mistake and it was committed. Hope this is ok.

**Comment by ntwb** [comment]
Hehehe yep, I just did the same thing in https://github.com/stylelint/jest-preset-stylelint/commit/6f79bc863ed43319ae93302922e4da00102dd0d5 😂
