### ISSUE TITLE
Fix TypeScript errors

### ISSUE THREAD

**Issue by jamonserrano** [stylelint/jest-preset-stylelint#44]
### What steps are needed to reproduce the bug?

Open the `index.d.ts` declaration file in VSCode or paste its contents in the TypeScript Sandbox:

https://www.typescriptlang.org/play?declaration=false#code/KYDwDg9gTgLgBDAnmYcAqwDOMDCBDTVAXjgG8AoASAHoAqWquW9AC1QGMIATVCAMwRsEWeOwLAAdI1rUqnHgC442KAEsAdgHMA3OSp0GlJnAAiWdmrAxVEdXH6DUMEXDGEpRmVR6YLqqzbqAPxKKho6ejT00nAAsnhgmAgQcABSIgDkSQAGztgStgA2iNkSpsB8eACuhTBK2ZWFhKXSMQAChKgsMDCJCtTUAFYig5gSNtRcEOyY1MDq1AmqAMR5MEWI6ngAtsAAtHzqe9a7EFUw0rKUGyFwAEYQEIXAeOq6+tGecQlJ62mZOTWEkwAGt-KVypUanU4A08E1gC1PO1OnBur1MP0hiMxhMpjNFmAVmtQf4trsDupLlRSWBbg8ni83uQAL7vUCQWAIZCoACC7HYwCsGGw+EIcBIItw4nZ4Gg8CQKDgAHU8FB1OEJWQPoZjABRcDAdjOLhwXaYTB4TSoPhQCDbRzCbCucRlACqmCq8OKcA58uAptt9sdYEKVU0Gg8xgA8gFbPC4KoBNkAO5qjVaTDZRNJKqELhRryUc2W623MJad5RXXMA0oY0BuCFDSodRVbZ3YBQewCGBCNPq8KFq7N9TAW5tjtdqsGGJ1o0m1xPdt2Sed7sOPuoAcZzTDuTL7bBJRr6eRWdfecN03zU2j1vt9c9x07ofUyi3gAyLYnj7POrnQ1r19dRTU4MMjzgU8N17ft0zfTwrlvHBD2PKC-ygXQ2T0WdjA9JwhFTeDM2zMA7RQWBEAAGjgKA8C3bs+1eWESytREaOye9sho15TWycCV248hjCTR01hdcVVCSDkF0bP4yO4KpBTNaACOY2xt2IvdhK8P0uUVVAACVgGGY0pTFYh0BECy4AAMioVVBy0OztUoasqEvIDFz4VQQEbeReFgpwXDcSQ4Fjax40KRNkx8kBsyk9QMngXIoCqREPEQjy4oDcsYDUStInctzjBMWxktcNh2BBR0Gl8gNswCsozChWp6kaZpMqYK5KCqdQ4rwO5nnpR5nleKtiq+Rzd3sO5TJgJJOHUGA8A0TUZOA7JWOtbjYS4uBeNhASj2zYAYHYLrmAiwIE1ErasFLREczgPMA0unrX0zW5pvCABtABdXRKGw8g9IVHkrOwABldg2G2PAtQoYrjAAOR2QLHTS557mATU1jeuAPS9QofTBxsgwdLc4FDcNI3fLHgDR3ZQny8IZ0+YwUP61RNGSamCF+FIqYZ-dKCWnzNCUPqQXUCAU2ZACvn5QUrCdURxDGd88AFIUYFuZXdfM8QAfZms4GM+a1YkrBRagEyF1uC2FyNwgTfPDnmDQKp1XsOxqnWOLmoqao2thDqMvfOKRsZcb3bN+JEj5qGkGeUcYCyWEaYjdQsyXbnNG9+jAmp8iuyQQsYgABXolg+apnzsaY+Awd+IQs40Wb5pou3CiLgA3JwhaEO0IBgQtCc9b1EETdPW9QS1dn5vsDqSBGttW9RSNLyjEzsdukpyMBtZBNiJFGWwkSYGIAEkBEQM4MjttXNQR-f+eqmjVFnkMa7roQG7Us3OUsA54HSgHRaeDg34QDmguTWyIvjXSip-ZM+9c4QDjHYNMSQj4WjkikPAXA+6vEFGBWwEtC6RSwV-Wu2RrQwClIZGowAAAUABKS+ZsOjAC6D0PoAxsCIFThoMeExXpQD2AXVQPBqDix5t7YAyw0HvjQXlAqvMAA+yhWZaDdorYwCdBZwGTkI4AacM78TzOsbYUNNgrXivYTBFcvjcN4RiLEgjhHLXGBAag4jJFVGkcAPxj1qAYKoZgZY7ArH2kwHYvAIB3zROwPaWxy0ElqLZnHGIhik4pzMSIixAUABiqhnjkieuEwIzjjCuLRHwzEAj8lpx8SErsASgkhLYmEzBkSAoAIqUk7gwBSnlPRpkwq+jmC5L+OkbAFigQbAhC1EOMI4QIk4SiHh9T3EDGGNgUYrT8SzHmISYkIgNgVMpMcVQpxzjvhuEoBkY0FbI2mT8Pmczv65BEMCMEYBlnB2hO1eEnVWguNROifh2IDm4l8ccs5qwRC0iuYcd8tJo4vKwu8XCnsXAIwZnAFMNDHSYHrEmVQjZfBwzwFIbqoNgHwB4OwXuT8+B9WNMXNYTDngsOpcAeGSgpQwxpWwpQfcIDSJxdETmdt6KoDXty5h7DszsvUJy2wRKSWvGnmSo0FLGxoLpbpRlcA1UarsPQxhyqqm2EwLcUg1MwzZ3tUKkQIqBV4F+hkNBGR-pwBZGK7kKBNwiB5cAd4zLWWoE0IUGBCYkbEMYmG5hSgDKhuwOGrC5AgA

### What did you expect to happen?

There shouldn't be any errors.

### What actually happened?

There are two errors. You can ignore the first one on line 157 as this is a declaration file, but the second one on line 160 seems to be an actual issue: `'testRule' is referenced directly or indirectly in its own type annotation.`

It causes a TypeScript build error in my project and also prevents the analysis of the `testRule()` parameters.

I managed to fix this by using a `TestRule` type:

```diff
/**
 * Test a rule with the specified schema.
 */
- export declare function testRule(schema: TestSchema): void;
+ type TestRule = (schema: TestSchema) => void;

/**
 * Create a `testRule()` function with any specified plugins.
 */
- export function getTestRule(options?: { plugins?: TestSchema['plugins'] }): typeof testRule;
+ export function getTestRule(options?: { plugins?: TestSchema['plugins'] }): TestRule;

declare global {
-	var testRule: typeof testRule;
+	var testRule: TestRule;
}
```

With this change the build succeeds and my editor duly complains when I try to use `testRule()` incorrectly.

**Comment by jeddy3** [comment]
@jamonserrano Thanks for the report. If you have time, please consider contributing a pull request to fix the issue.
