### ISSUE TITLE
Assert plugin options validation

### ISSUE THREAD

**Issue by AndyOGo** [stylelint/jest-preset-stylelint#58]
### What is the problem you're trying to solve?

I want to assert my plugins options validation.

[`stylelint-test-rule-tape`](https://github.com/stylelint/stylelint-test-rule-tape) allowed to `reject` for invalid options.

This doesn't work anymore with jest.

### What solution would you like to see?

The same behavior of invalid plugin options with `reject` as it was working in [`stylelint-test-rule-tape`](https://github.com/stylelint/stylelint-test-rule-tape).

The resolved promise of the `lint()` API holds that data in [`invalidOptionWarnings`](https://github.com/stylelint/stylelint/search?q=invalidOptionWarnings).

**Comment by ybiquitous** [comment]
@AndyOGo Thanks for the report and the pull request. SGTM 👍🏼

**Comment by AndyOGo** [comment]
Glad to help.
Thank you for this awesome tool!
